version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      monitoring:
        aliases:
          - prometheus
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    user: "nobody"
    security_opt:
      - no-new-privileges:true

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "127.0.0.1:9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://167.71.155.226:9093'
      - '--cluster.advertise-address=0.0.0.0:9093'
    restart: unless-stopped
    networks:
      monitoring:
        aliases:
          - alertmanager
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    user: "nobody"
    security_opt:
      - no-new-privileges:true

  alert-bridge:
    build: ./alert-bridge
    container_name: alert-bridge
    ports:
      - "127.0.0.1:9095:9094"
    volumes:
      - ./alert-bridge/config:/app/config:ro
    environment:
      - MATTERMOST_WEBHOOK_URL=http://138.68.249.92:8065/hooks/ou4n5jny43fp5mttzmdokpuh1a
    restart: unless-stopped
    networks:
      monitoring:
        aliases:
          - alert-bridge
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    user: "nobody"
    security_opt:
      - no-new-privileges:true

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "127.0.0.1:9115:9115"
    volumes:
      - ./blackbox:/config:ro
    command:
      - '--config.file=/config/blackbox.yml'
    restart: unless-stopped
    networks:
      monitoring:
        aliases:
          - blackbox
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    user: "nobody"
    security_opt:
      - no-new-privileges:true

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "127.0.0.1:9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.wifi'
      - '--no-collector.hwmon'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.meminfo'
      - '--collector.loadavg'
      - '--collector.netstat'
    restart: unless-stopped
    networks:
      monitoring:
        aliases:
          - node-exporter
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    user: "nobody"
    security_opt:
      - no-new-privileges:true

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SERVER_ROOT_URL=http://167.71.155.226:3001
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
    restart: unless-stopped
    networks:
      monitoring:
        aliases:
          - grafana
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    user: "grafana"
    security_opt:
      - no-new-privileges:true

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local 