global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/website_alerts.yml"

scrape_configs:
  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://acronymmeaning.com
        labels:
          what: blackbox_target
          site: acronymmeaning
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115

  - job_name: nextjs
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - host.docker.internal:3000
        labels:
          what: nextjs_target
          site: acronymmeaning

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
        labels:
          site: acronymmeaning
