groups:
  - name: website_alerts
    rules:
      - alert: WebsiteDown
        expr: up{job="acronymmeaning"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Website {{ $labels.instance }} is down"
          description: "Website {{ $labels.instance }} has been down for more than 1 minute."

      - alert: HighResponseTime
        expr: http_request_duration_seconds{job="acronymmeaning"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time on {{ $labels.instance }}"
          description: "Website {{ $labels.instance }} has a response time above 2 seconds for more than 5 minutes."

      - alert: HighErrorRate
        expr: rate(http_requests_total{job="acronymmeaning", status=~"5.."}[5m]) / rate(http_requests_total{job="acronymmeaning"}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on {{ $labels.instance }}"
          description: "Website {{ $labels.instance }} has an error rate above 5% for more than 5 minutes."
          
      - alert: SSLCertificateExpiringSoon
        expr: ssl_cert_not_after{job="acronymmeaning"} - time() < 86400 * 30
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate for {{ $labels.instance }} is expiring soon"
          description: "SSL certificate for {{ $labels.instance }} will expire in {{ $value | humanizeDuration }}."
          
      - alert: SSLCertificateExpired
        expr: ssl_cert_not_after{job="acronymmeaning"} - time() < 0
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: "SSL certificate for {{ $labels.instance }} has expired"
          description: "SSL certificate for {{ $labels.instance }} has expired {{ $value | humanizeDuration }} ago."
          
      - alert: DNSResolutionFailed
        expr: dns_lookup_seconds{job="acronymmeaning"} == -1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "DNS resolution failed for {{ $labels.instance }}"
          description: "DNS resolution for {{ $labels.instance }} has been failing for more than 5 minutes."
          
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage on {{ $labels.instance }} is above 80% for more than 5 minutes."
          
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage on {{ $labels.instance }} is above 85% for more than 5 minutes."
          
      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage on {{ $labels.instance }} is above 90% for more than 5 minutes."
          
      - alert: ServiceDown
        expr: up{job=~"prometheus|grafana|alertmanager"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."
          
      - alert: NetworkErrors
        expr: rate(node_network_receive_errs_total[5m]) + rate(node_network_transmit_errs_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Network errors on {{ $labels.instance }}"
          description: "Network errors detected on {{ $labels.instance }} for more than 5 minutes."
          
      - alert: ContainerUnhealthy
        expr: container_last_seen{job="node-exporter"} - time() > 300
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} is unhealthy"
          description: "Container {{ $labels.name }} has not been seen for more than 5 minutes." 