{
 "title": "SSL Certificate Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SSL Certificate Expiration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dtduration" }
   ],
   "targets": [
    {
     "expr": "ssl_cert_not_after{job=\"acronymmeaning\"} - time()",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL Certificate Valid From",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dateTimeAsLocal" }
   ],
   "targets": [
    {
     "expr": "ssl_cert_not_before{job=\"acronymmeaning\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL Certificate Valid Until",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "dateTimeAsLocal" }
   ],
   "targets": [
    {
     "expr": "ssl_cert_not_after{job=\"acronymmeaning\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL Certificate Issuer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ssl_cert_issuer{job=\"acronymmeaning\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}